refresh = 9
version = 20180612.01

urls = ['https://al-akhbar.com/',
'https://al-akhbar.com/Lebanon',
'https://al-akhbar.com/Arab',
'https://al-akhbar.com/World',
'https://al-akhbar.com/Culture_People',
'https://al-akhbar.com/Sport',
'https://al-akhbar.com/Opinion',
'https://al-akhbar.com/Editions',
'https://al-akhbar.com/Lebanon',
'https://al-akhbar.com/Politics',
'https://al-akhbar.com/Economy',
'https://al-akhbar.com/Community',
'https://al-akhbar.com/Education',
'https://al-akhbar.com/Arab',
'https://al-akhbar.com/Palestine',
'https://al-akhbar.com/Syria',
'https://al-akhbar.com/Iraq',
'https://al-akhbar.com/Yemen',
'https://al-akhbar.com/Egypt',
'https://al-akhbar.com/Arab_Island',
'https://al-akhbar.com/Morocco',
'https://al-akhbar.com/World',
'https://al-akhbar.com/Europe',
'https://al-akhbar.com/Asia',
'https://al-akhbar.com/Africa',
'https://al-akhbar.com/America',
'https://al-akhbar.com/Culture_People',
'https://al-akhbar.com/Literature_Arts',
'https://al-akhbar.com/Theater',
'https://al-akhbar.com/Cinema',
'https://al-akhbar.com/Media_Tv',
'https://al-akhbar.com/Visual_Arts',
'https://al-akhbar.com/Celebrities',
'https://al-akhbar.com/Sport',
'https://al-akhbar.com/Sport_Olympics',
'https://al-akhbar.com/Sport_Lebanon',
'https://al-akhbar.com/Sport_World',
'https://al-akhbar.com/World_Cup',
'https://al-akhbar.com/Enviroment',
'https://al-akhbar.com/Health',
'https://al-akhbar.com/Technology',
'https://al-akhbar.com/Opinion',
'https://al-akhbar.com/Last_Page',
'https://al-akhbar.com/Finance_Markets',
'https://al-akhbar.com/PhotoBlogs',]
regex = [r'^https?:\/\/[^\/]*al\-akhbar\.com\/']	
videoregex = []
liveregex = []
